### ISSUE TITLE
cancel not working

### ISSUE THREAD

**Issue by Freundschaft** [Freundschaft/calendso#4]
cancel isnt working

**Comment by Freundschaft** [comment]
[GET] /cancel/pNX1xWGNSnH3zakXzyY4Hp
14:01:03:33
2021-08-22T11:01:04.113Z	93c4c584-e8ac-434b-8499-97c06cf0c34b	ERROR	TypeError: Cannot read property 'length' of null
    at Type (/var/task/.next/server/pages/cancel/[uid].js:190:43)
    at d (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
    at a.b.read (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at exports.renderToString (/var/task/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/var/task/node_modules/next/dist/next-server/server/render.js:54:854)
    at Function.getInitialProps (/var/task/.next/server/pages/_document.js:543:19)
    at loadGetInitialProps (/var/task/node_modules/next/dist/next-server/lib/utils.js:5:101)
    at renderToHTML (/var/task/node_modules/next/dist/next-server/server/render.js:54:1145)
RequestId: 93c4c584-e8ac-434b-8499-97c06cf0c34b Error: Runtime exited with error: exit status 1
Runtime.ExitError

**Comment by PeerRich** [comment]
should be fixed in v.1.0 🙏
